"""first migration

Revision ID: 765528777cbd
Revises: 
Create Date: 2025-11-30 23:59:17.349810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765528777cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
